version: '3.1'

services:
  dockerized-mysql:
    image: mysql:latest
    restart: always
    container_name: "sqms-mysql"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234


  dockerized-sqms:
    build: .
    image: sqms:latest
    container_name: "sqms-app"
    ports:
      - "8081:8080"
    depends_on:
      - dockerized-mysql

